import type { AdminJob, Asset, CreditLedgerEvent, CurrentUser, Job, Plan, Skill } from "@/types";

export const currentUser: CurrentUser = {
  name: "Vipeo Creator",
  email: "creator@vipeo.demo",
  plan: "Pro",
  credits: 1240,
  subscriptionStatus: "active",
};

export const launchSkills: Skill[] = [
  {
    id: "hot-news-faceless",
    name: "Hot news faceless",
    line: "B",
    type: "Video B",
    industry: "News creator",
    platforms: ["YouTube", "TikTok"],
    ratio: "16:9 / 9:16",
    duration: "45-90s",
    priority: "MVP",
    version: "1.0.0",
    status: "live",
    creditEstimate: 120,
    description: "Turn a breaking topic into a narrated faceless news video with visuals, subtitles, and a clear source-check reminder.",
    inputs: ["Topic", "Region", "Tone", "Target platform"],
    complianceNote: "News-style outputs need source review before publishing.",
  },
  {
    id: "fun-facts-top-5",
    name: "Fun facts / Top 5",
    line: "B",
    type: "Video B",
    industry: "Entertainment creator",
    platforms: ["TikTok", "Reels", "Shorts"],
    ratio: "9:16",
    duration: "30-60s",
    priority: "MVP",
    version: "1.0.0",
    status: "live",
    creditEstimate: 95,
    description: "Create a fast vertical list video with hook, visuals, voice, captions, and CTA.",
    inputs: ["Topic", "Audience", "Tone", "CTA"],
  },
  {
    id: "clean-talking-head-edit",
    name: "Clean talking-head edit",
    line: "Edit",
    type: "Edit",
    industry: "Talking-head creator",
    platforms: ["YouTube", "TikTok", "Reels"],
    ratio: "16:9 / 9:16",
    duration: "Input-based",
    priority: "MVP",
    version: "1.0.0",
    status: "live",
    creditEstimate: 60,
    description: "Clean cuts, captions, silence trimming, and brand-safe formatting for owned footage.",
    inputs: ["Owned video", "Caption style", "Output ratio"],
    complianceNote: "Only upload video you own or have permission to edit.",
  },
  {
    id: "livestream-short-clips",
    name: "Live stream → short clips",
    line: "Edit",
    type: "Edit",
    industry: "Livestreamer / seller",
    platforms: ["TikTok", "Reels"],
    ratio: "9:16",
    duration: "15-45s clips",
    priority: "MVP",
    version: "1.0.0",
    status: "live",
    creditEstimate: 80,
    description: "Find highlight moments from owned live footage and format them as short clips.",
    inputs: ["Owned livestream", "Clip count", "Highlight type"],
    complianceNote: "Only upload streams you own or have permission to reuse.",
  },
  {
    id: "fast-hook-preset",
    name: "Fast-hook preset",
    line: "Edit",
    type: "Edit",
    industry: "Creator / seller",
    platforms: ["TikTok", "Reels", "Shorts"],
    ratio: "9:16",
    duration: "5-15s intro",
    priority: "MVP",
    version: "1.0.0",
    status: "live",
    creditEstimate: 35,
    description: "Generate and attach a high-retention intro hook for a short video.",
    inputs: ["Video goal", "Audience", "Offer"],
  },
  {
    id: "auto-subtitles",
    name: "Auto subtitles",
    line: "Edit",
    type: "Edit",
    industry: "Creator / educator / seller",
    platforms: ["All"],
    ratio: "All ratios",
    duration: "Input-based",
    priority: "MVP",
    version: "1.0.0",
    status: "live",
    creditEstimate: 40,
    description: "Generate readable captions with language-aware phrasing and export-ready styling.",
    inputs: ["Owned video", "Language", "Caption style"],
  },
  {
    id: "smart-image-generation",
    name: "Smart image generation",
    line: "Image",
    type: "Image",
    industry: "Everyone",
    platforms: ["Social", "Ads", "Web"],
    ratio: "Multi-ratio",
    duration: "Still image",
    priority: "MVP",
    version: "1.0.0",
    status: "live",
    creditEstimate: 25,
    description: "Create niche-aware images from a prompt, product idea, or campaign need.",
    inputs: ["Prompt", "Style", "Ratio"],
  },
  {
    id: "marketplace-shop-banner",
    name: "Marketplace shop banner",
    line: "Banner",
    type: "Banner",
    industry: "Online seller",
    platforms: ["Marketplace", "Social"],
    ratio: "1:1 / vertical",
    duration: "Still banner",
    priority: "MVP",
    version: "1.0.0",
    status: "live",
    creditEstimate: 30,
    description: "Generate offer banners for marketplace shops with product-first copy.",
    inputs: ["Product", "Offer", "Brand colors"],
  },
  {
    id: "fnb-local-shop-banner",
    name: "F&B / local shop banner",
    line: "Banner",
    type: "Banner",
    industry: "F&B / small business",
    platforms: ["Social", "Story"],
    ratio: "1:1 / 9:16",
    duration: "Still banner",
    priority: "MVP",
    version: "1.0.0",
    status: "live",
    creditEstimate: 30,
    description: "Create menu, promo, and opening-hour banners for local shops.",
    inputs: ["Dish or promo", "Price", "CTA"],
  },
  {
    id: "spa-salon-gym-banner",
    name: "Spa / salon / gym banner",
    line: "Banner",
    type: "Banner",
    industry: "Local services",
    platforms: ["Social", "Story"],
    ratio: "1:1 / 9:16",
    duration: "Still banner",
    priority: "MVP",
    version: "1.0.0",
    status: "live",
    creditEstimate: 30,
    description: "Create service promo banners with safe, non-medical claims.",
    inputs: ["Service", "Offer", "Brand tone"],
    complianceNote: "Avoid medical or guaranteed-result claims.",
  },
  {
    id: "real-estate-banner",
    name: "Real-estate banner",
    line: "Banner",
    type: "Banner",
    industry: "Property broker",
    platforms: ["Social", "Web"],
    ratio: "1:1 / 16:9",
    duration: "Still banner",
    priority: "MVP",
    version: "1.0.0",
    status: "live",
    creditEstimate: 35,
    description: "Create listing and project-update banners with compliance-safe wording.",
    inputs: ["Listing facts", "Location", "CTA"],
    complianceNote: "Use verified property facts only.",
  },
  {
    id: "mood-background-music",
    name: "Mood-based background music",
    line: "Music",
    type: "Music",
    industry: "Any creator",
    platforms: ["Video overlay"],
    ratio: "Audio",
    duration: "15-90s",
    priority: "MVP",
    version: "1.0.0",
    status: "live",
    creditEstimate: 20,
    description: "Generate or select background music by mood, tempo, and platform use.",
    inputs: ["Mood", "Tempo", "Duration"],
  },
];

export const roadmapSkills: Skill[] = [
  {
    id: "brand-mascot-animation",
    name: "Brand mascot animation",
    line: "A",
    type: "2D animation",
    industry: "Shops / F&B / small business",
    platforms: ["TikTok", "Reels", "YouTube"],
    ratio: "9:16 / 16:9",
    duration: "30-60s",
    priority: "P2",
    version: "0.1.0",
    status: "coming-soon",
    creditEstimate: 240,
    description: "Talking mascot workflow after animation/lip-sync quality is stable.",
    inputs: ["Mascot image", "Script", "Voice"],
  },
  {
    id: "ugc-avatar-sales",
    name: "UGC avatar sales video",
    line: "C",
    type: "Avatar",
    industry: "Marketplace seller",
    platforms: ["TikTok", "Reels"],
    ratio: "9:16",
    duration: "30-60s",
    priority: "ROADMAP",
    version: "0.1.0",
    status: "coming-soon",
    creditEstimate: 320,
    description: "Virtual presenter sales video; deferred because likeness consent and cost are high.",
    inputs: ["Product", "Avatar consent", "Script"],
    complianceNote: "Requires explicit likeness consent and synthetic presenter labeling.",
  },
];

export const recentJobs: Job[] = [
  { id: "job_1001", title: "Top 5 AI video trends for creators", skillId: "fun-facts-top-5", status: "completed", progress: 100, locale: "en", ratio: "9:16", duration: "45s", creditsReserved: 95, creditsFinal: 88, createdAt: "2026-07-03 09:12", resultUrl: "#" },
  { id: "job_1002", title: "Vietnam retail news recap", skillId: "hot-news-faceless", status: "running", progress: 62, locale: "vi", ratio: "16:9", duration: "60s", creditsReserved: 120, creditsFinal: 0, createdAt: "2026-07-03 10:04" },
  { id: "job_1003", title: "Summer drink promo banner", skillId: "fnb-local-shop-banner", status: "queued", progress: 15, locale: "vi", ratio: "9:16", duration: "Still", creditsReserved: 30, creditsFinal: 0, createdAt: "2026-07-03 10:21" },
  { id: "job_1004", title: "Unlicensed movie dub request", skillId: "auto-subtitles", status: "needs_review", progress: 40, locale: "en", ratio: "16:9", duration: "Input-based", creditsReserved: 40, creditsFinal: 0, createdAt: "2026-07-03 10:32", failureReason: "Rights gate needs confirmation before processing." },
];

export const assets: Asset[] = [
  { id: "asset_2001", jobId: "job_1001", title: "Top 5 AI video trends", kind: "video", locale: "en", ratio: "9:16", duration: "45s", platform: "TikTok / Reels", aiLabel: "AI-generated video. Synthetic voice used.", planGate: "Pro export: no Vipeo watermark" },
  { id: "asset_2002", jobId: "job_1003", title: "Summer drink promo", kind: "banner", locale: "vi", ratio: "9:16", platform: "Story", aiLabel: "AI-generated image." },
];

export const creditLedger: CreditLedgerEvent[] = [
  { id: "ledger_1", type: "purchase", amount: 1500, balanceAfter: 1500, label: "Pro monthly credit grant", createdAt: "2026-07-01" },
  { id: "ledger_2", type: "reserve", amount: -95, balanceAfter: 1405, label: "Reserved for Top 5 video", createdAt: "2026-07-03" },
  { id: "ledger_3", type: "finalize", amount: 7, balanceAfter: 1412, label: "Unused credits released", createdAt: "2026-07-03" },
  { id: "ledger_4", type: "reserve", amount: -120, balanceAfter: 1292, label: "Reserved for news render", createdAt: "2026-07-03" },
];

export const plans: Plan[] = [
  { id: "free", name: "Free", price: "$0", credits: 100, status: "active", features: ["Watermarked exports", "Starter skill access", "Community queue"] },
  { id: "pro", name: "Pro", price: "$19/mo", credits: 1500, status: "active", features: ["12 launch skills", "Priority queue", "No watermark on Pro exports", "English + Vietnamese UI"] },
  { id: "business", name: "Business", price: "Waitlist", credits: 6000, status: "coming-soon", features: ["Team workspace", "Brand kit", "Member credit limits"] },
  { id: "api", name: "API", price: "Waitlist", credits: 0, status: "coming-soon", features: ["Bring-your-own model keys", "Workflow API", "Custom SLAs"] },
];

export const adminJobs: AdminJob[] = [
  { id: "job_1002", user: "creator@vipeo.demo", skill: "Hot news faceless", status: "running", credits: 120, risk: "medium", action: "Watch source-check step" },
  { id: "job_1004", user: "agency@vipeo.demo", skill: "Auto subtitles", status: "needs_review", credits: 40, risk: "high", action: "Confirm upload rights" },
  { id: "job_1001", user: "creator@vipeo.demo", skill: "Fun facts / Top 5", status: "completed", credits: 88, risk: "low", action: "No action" },
];

export const helpTopics = [
  { title: "What is a skill?", body: "A Vipeo skill is a packaged creative workflow: style, prompt, script, model config, voice/music defaults, ratio, cost, and output." },
  { title: "How credits work", body: "Vipeo reserves estimated credits before rendering, finalizes actual cost after completion, and releases unused credits back to the wallet." },
  { title: "AI labels and consent", body: "Outputs should disclose AI-generated media, synthetic voices, dubbing, or avatar usage where required." },
  { title: "Why some jobs need review", body: "Uploads, voice, likeness, news, health, real estate, or copyrighted material can require rights confirmation or manual review." },
];
